export const SupplyChainSourceAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "FRAUD_TIME_WINDOW",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_HUMIDITY",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_SCANS_IN_WINDOW",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_TEMPERATURE",
    inputs: [],
    outputs: [{ name: "", type: "int256", internalType: "int256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "addLogistics",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addManufacturer",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addOracle",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedLogistics",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedManufacturers",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedOracles",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "confirmDelivery",
    inputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "location", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createItem",
    inputs: [
      { name: "rfidTag", type: "string", internalType: "string" },
      { name: "originLocation", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "flagItem",
    inputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAllItemIds",
    inputs: [],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getItem",
    inputs: [{ name: "id", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SupplyChainSource.Item",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "manufacturer", type: "address", internalType: "address" },
          {
            name: "currentCustodian",
            type: "address",
            internalType: "address",
          },
          {
            name: "status",
            type: "uint8",
            internalType: "enum SupplyChainSource.Status",
          },
          { name: "exists", type: "bool", internalType: "bool" },
          { name: "lastLocation", type: "string", internalType: "string" },
          { name: "lastScanTime", type: "uint256", internalType: "uint256" },
          { name: "lastScanner", type: "address", internalType: "address" },
          { name: "scanCount", type: "uint256", internalType: "uint256" },
          { name: "windowStart", type: "uint256", internalType: "uint256" },
          {
            name: "lastReading",
            type: "tuple",
            internalType: "struct SupplyChainSource.SensorReading",
            components: [
              { name: "temperature", type: "int256", internalType: "int256" },
              { name: "humidity", type: "uint256", internalType: "uint256" },
              { name: "tiltDetected", type: "bool", internalType: "bool" },
              { name: "timestamp", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "rfidTag", type: "string", internalType: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getItemByRFID",
    inputs: [{ name: "rfidTag", type: "string", internalType: "string" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SupplyChainSource.Item",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "manufacturer", type: "address", internalType: "address" },
          {
            name: "currentCustodian",
            type: "address",
            internalType: "address",
          },
          {
            name: "status",
            type: "uint8",
            internalType: "enum SupplyChainSource.Status",
          },
          { name: "exists", type: "bool", internalType: "bool" },
          { name: "lastLocation", type: "string", internalType: "string" },
          { name: "lastScanTime", type: "uint256", internalType: "uint256" },
          { name: "lastScanner", type: "address", internalType: "address" },
          { name: "scanCount", type: "uint256", internalType: "uint256" },
          { name: "windowStart", type: "uint256", internalType: "uint256" },
          {
            name: "lastReading",
            type: "tuple",
            internalType: "struct SupplyChainSource.SensorReading",
            components: [
              { name: "temperature", type: "int256", internalType: "int256" },
              { name: "humidity", type: "uint256", internalType: "uint256" },
              { name: "tiltDetected", type: "bool", internalType: "bool" },
              { name: "timestamp", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "rfidTag", type: "string", internalType: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getNumberOfItems",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getStatus",
    inputs: [{ name: "id", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "uint8",
        internalType: "enum SupplyChainSource.Status",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "handoffItem",
    inputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "newCustodian", type: "address", internalType: "address" },
      { name: "location", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "itemCounter",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "items",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "manufacturer", type: "address", internalType: "address" },
      { name: "currentCustodian", type: "address", internalType: "address" },
      {
        name: "status",
        type: "uint8",
        internalType: "enum SupplyChainSource.Status",
      },
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "lastLocation", type: "string", internalType: "string" },
      { name: "lastScanTime", type: "uint256", internalType: "uint256" },
      { name: "lastScanner", type: "address", internalType: "address" },
      { name: "scanCount", type: "uint256", internalType: "uint256" },
      { name: "windowStart", type: "uint256", internalType: "uint256" },
      {
        name: "lastReading",
        type: "tuple",
        internalType: "struct SupplyChainSource.SensorReading",
        components: [
          { name: "temperature", type: "int256", internalType: "int256" },
          { name: "humidity", type: "uint256", internalType: "uint256" },
          { name: "tiltDetected", type: "bool", internalType: "bool" },
          { name: "timestamp", type: "uint256", internalType: "uint256" },
        ],
      },
      { name: "rfidTag", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "removeLogistics",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeManufacturer",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeOracle",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "reportConditions",
    inputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "temperature", type: "int256", internalType: "int256" },
      { name: "humidity", type: "uint256", internalType: "uint256" },
      { name: "tiltDetected", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rfidToItemId",
    inputs: [{ name: "", type: "string", internalType: "string" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "scanItem",
    inputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "location", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ConditionBreached",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "breachType",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "details",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FraudDetected",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "flaggedBy",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ItemCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "manufacturer",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "rfidTag",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ItemDelivered",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "receiver",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "location",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ItemHandedOff",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "from",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      { name: "to", type: "address", indexed: false, internalType: "address" },
      {
        name: "location",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ItemScanned",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "scanner",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "location",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "timestamp",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SensorDataReported",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      {
        name: "temperature",
        type: "int256",
        indexed: false,
        internalType: "int256",
      },
      {
        name: "humidity",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "tilt", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
] as const;

export const supplyChainAddress =
  "0x0c524712a77aD9F72F6482F66e3845382675A3E3" as const; // BaseSepoliia address

export const SupplyChainTokenAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "initialSupply", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BURNER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "DEFAULT_ADMIN_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MINTER_ROLE",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "addBurner",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addMinter",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "burnCrossChain",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "destinationChainId", type: "uint256", internalType: "uint256" },
      { name: "nonce", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "transferId", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fundEscrowCrossChain",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "destinationChainId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "transferId", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getRoleAdmin",
    inputs: [{ name: "role", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "grantRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mintCrossChain",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "processedFundRequests",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "processedTransfers",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "callerConfirmation", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeRole",
    inputs: [
      { name: "role", type: "bytes32", internalType: "bytes32" },
      { name: "account", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "spender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EscrowFundRequest",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "wholesaler",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "sourceChainId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "destinationChainId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleAdminChanged",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "previousAdminRole",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "newAdminRole",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleGranted",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoleRevoked",
    inputs: [
      { name: "role", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokensBurned",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "destinationChainId",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
      {
        name: "transferId",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokensMinted",
    inputs: [
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AccessControlBadConfirmation", inputs: [] },
  {
    type: "error",
    name: "AccessControlUnauthorizedAccount",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "neededRole", type: "bytes32", internalType: "bytes32" },
    ],
  },
  {
    type: "error",
    name: "ERC20InsufficientAllowance",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "allowance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC20InsufficientBalance",
    inputs: [
      { name: "sender", type: "address", internalType: "address" },
      { name: "balance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC20InvalidApprover",
    inputs: [{ name: "approver", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidReceiver",
    inputs: [{ name: "receiver", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidSender",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidSpender",
    inputs: [{ name: "spender", type: "address", internalType: "address" }],
  },
] as const;

export const supplyChainTokenAddress =
  "0x1DE0046d87736c32DB5e10459F3409Afc5C3E0DE" as const;

export const supplyChainEscrowAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "tokenAddress", type: "address", internalType: "address" },
      { name: "_currentChainId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addOracle",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "authorizedOracles",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "confirmDelivery",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "confirmPickup",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createOrder",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "itemId", type: "uint256", internalType: "uint256" },
      { name: "carrierWallet", type: "address", internalType: "address" },
      { name: "carrierChainId", type: "uint256", internalType: "uint256" },
      { name: "wholesalerWallet", type: "address", internalType: "address" },
      { name: "wholesalerChainId", type: "uint256", internalType: "uint256" },
      { name: "manufacturerChainId", type: "uint256", internalType: "uint256" },
      { name: "orderValue", type: "uint256", internalType: "uint256" },
      { name: "location", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "currentChainId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "depositCarrierBond",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "shippingFee", type: "uint256", internalType: "uint256" },
      { name: "carrierDeposit", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fundEscrow",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fundEscrowByOracle",
    inputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "wholesaler", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getEscrowBalance",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrder",
    inputs: [{ name: "orderId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SupplyChainEscrow.Order",
        components: [
          { name: "orderId", type: "uint256", internalType: "uint256" },
          { name: "itemId", type: "uint256", internalType: "uint256" },
          {
            name: "manufacturer",
            type: "tuple",
            internalType: "struct SupplyChainEscrow.Party",
            components: [
              { name: "wallet", type: "address", internalType: "address" },
              { name: "chainId", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "carrier",
            type: "tuple",
            internalType: "struct SupplyChainEscrow.Party",
            components: [
              { name: "wallet", type: "address", internalType: "address" },
              { name: "chainId", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "wholesaler",
            type: "tuple",
            internalType: "struct SupplyChainEscrow.Party",
            components: [
              { name: "wallet", type: "address", internalType: "address" },
              { name: "chainId", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "orderValue", type: "uint256", internalType: "uint256" },
          { name: "shippingFee", type: "uint256", internalType: "uint256" },
          { name: "carrierDeposit", type: "uint256", internalType: "uint256" },
          {
            name: "status",
            type: "uint8",
            internalType: "enum SupplyChainEscrow.OrderStatus",
          },
          {
            name: "liableParty",
            type: "uint8",
            internalType: "enum SupplyChainEscrow.LiableParty",
          },
          { name: "exists", type: "bool", internalType: "bool" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "pickedUpAt", type: "uint256", internalType: "uint256" },
          { name: "deliveredAt", type: "uint256", internalType: "uint256" },
          { name: "breachReason", type: "string", internalType: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrderByItem",
    inputs: [{ name: "itemId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SupplyChainEscrow.Order",
        components: [
          { name: "orderId", type: "uint256", internalType: "uint256" },
          { name: "itemId", type: "uint256", internalType: "uint256" },
          {
            name: "manufacturer",
            type: "tuple",
            internalType: "struct SupplyChainEscrow.Party",
            components: [
              { name: "wallet", type: "address", internalType: "address" },
              { name: "chainId", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "carrier",
            type: "tuple",
            internalType: "struct SupplyChainEscrow.Party",
            components: [
              { name: "wallet", type: "address", internalType: "address" },
              { name: "chainId", type: "uint256", internalType: "uint256" },
            ],
          },
          {
            name: "wholesaler",
            type: "tuple",
            internalType: "struct SupplyChainEscrow.Party",
            components: [
              { name: "wallet", type: "address", internalType: "address" },
              { name: "chainId", type: "uint256", internalType: "uint256" },
            ],
          },
          { name: "orderValue", type: "uint256", internalType: "uint256" },
          { name: "shippingFee", type: "uint256", internalType: "uint256" },
          { name: "carrierDeposit", type: "uint256", internalType: "uint256" },
          {
            name: "status",
            type: "uint8",
            internalType: "enum SupplyChainEscrow.OrderStatus",
          },
          {
            name: "liableParty",
            type: "uint8",
            internalType: "enum SupplyChainEscrow.LiableParty",
          },
          { name: "exists", type: "bool", internalType: "bool" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "pickedUpAt", type: "uint256", internalType: "uint256" },
          { name: "deliveredAt", type: "uint256", internalType: "uint256" },
          { name: "breachReason", type: "string", internalType: "string" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "itemToOrder",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orders",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "orderId", type: "uint256", internalType: "uint256" },
      { name: "itemId", type: "uint256", internalType: "uint256" },
      {
        name: "manufacturer",
        type: "tuple",
        internalType: "struct SupplyChainEscrow.Party",
        components: [
          { name: "wallet", type: "address", internalType: "address" },
          { name: "chainId", type: "uint256", internalType: "uint256" },
        ],
      },
      {
        name: "carrier",
        type: "tuple",
        internalType: "struct SupplyChainEscrow.Party",
        components: [
          { name: "wallet", type: "address", internalType: "address" },
          { name: "chainId", type: "uint256", internalType: "uint256" },
        ],
      },
      {
        name: "wholesaler",
        type: "tuple",
        internalType: "struct SupplyChainEscrow.Party",
        components: [
          { name: "wallet", type: "address", internalType: "address" },
          { name: "chainId", type: "uint256", internalType: "uint256" },
        ],
      },
      { name: "orderValue", type: "uint256", internalType: "uint256" },
      { name: "shippingFee", type: "uint256", internalType: "uint256" },
      { name: "carrierDeposit", type: "uint256", internalType: "uint256" },
      {
        name: "status",
        type: "uint8",
        internalType: "enum SupplyChainEscrow.OrderStatus",
      },
      {
        name: "liableParty",
        type: "uint8",
        internalType: "enum SupplyChainEscrow.LiableParty",
      },
      { name: "exists", type: "bool", internalType: "bool" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "pickedUpAt", type: "uint256", internalType: "uint256" },
      { name: "deliveredAt", type: "uint256", internalType: "uint256" },
      { name: "breachReason", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "processedFundRequests",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resolveDispute",
    inputs: [
      { name: "itemId", type: "uint256", internalType: "uint256" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract ISupplyChainToken" },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CarrierBondDeposited",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "carrier",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "deposit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CarrierTermsSet",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "shippingFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "carrierDeposit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CrossChainPayment",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "recipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "destinationChainId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "transferId",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DeliveryConfirmed",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "wholesaler",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DisputeRaised",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "liable",
        type: "uint8",
        indexed: false,
        internalType: "enum SupplyChainEscrow.LiableParty",
      },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EscrowFunded",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "wholesaler",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EscrowFundedCrossChain",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "wholesaler",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ItemPickedUp",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "carrier",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderCreated",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "location",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "sourceChain",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderResolved",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "liable",
        type: "uint8",
        indexed: false,
        internalType: "enum SupplyChainEscrow.LiableParty",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SameChainPayment",
    inputs: [
      {
        name: "orderId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "recipient",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "reason",
        type: "string",
        indexed: false,
        internalType: "string",
      },
    ],
    anonymous: false,
  },
] as const;

export const supplyChainEscrowAddress =
  "0x29CE120E1246E8ea6e3BaAf3AEcd4be58582f526" as const;

export const supplyChainTokenAddress2 =
  "0xC3BaE3b62e56b451a1aA5C96e50B859FfC20340a" as const;
